default_language_version:
  python: python3.7

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.0
    hooks:
      - id: check-yaml
        exclude: .github/
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort -y --settings-path ./pyproject.toml
        types: [python]
        language: system

  - repo: local

    hooks:
      - id: black
        name: black
        entry: poetry run black --config ./pyproject.toml
        types: [python]
        language: system
        # args: [--config, ./pyproject.toml]
